[2021-08-17 17:01:05,377] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-91fb5c23-5af1-44d7-b9c7-468f594cf6e5] in group order has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:01:05,379] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 11 (__consumer_offsets-0) (reason: removing member consumer-3-91fb5c23-5af1-44d7-b9c7-468f594cf6e5 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:01:05,379] INFO [GroupCoordinator 0]: Group order with generation 12 is now empty (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:02:48,106] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group order in Empty state. Created a new member id consumer-3-d586858d-e14b-4d5f-a443-724427ce9d1b for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:02:48,106] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 12 (__consumer_offsets-0) (reason: Adding new member consumer-3-d586858d-e14b-4d5f-a443-724427ce9d1b with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:02:48,107] INFO [GroupCoordinator 0]: Stabilized group order generation 13 (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:02:48,111] INFO [GroupCoordinator 0]: Assignment received from leader for group order for generation 13 (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:03:10,799] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-08-17 17:03:37,268] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-console-consumer-91105-1-1027be48-4b28-474d-a268-abd0f9b6b04a] in group console-consumer-91105 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:03:37,269] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-91105 in state PreparingRebalance with old generation 1 (__consumer_offsets-37) (reason: removing member consumer-console-consumer-91105-1-1027be48-4b28-474d-a268-abd0f9b6b04a on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:03:37,269] INFO [GroupCoordinator 0]: Group console-consumer-91105 with generation 2 is now empty (__consumer_offsets-37) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:04:32,374] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-d586858d-e14b-4d5f-a443-724427ce9d1b] in group order has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:04:32,375] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 13 (__consumer_offsets-0) (reason: removing member consumer-3-d586858d-e14b-4d5f-a443-724427ce9d1b on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:04:32,375] INFO [GroupCoordinator 0]: Group order with generation 14 is now empty (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:04:50,556] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-23376 in state PreparingRebalance with old generation 0 (__consumer_offsets-12) (reason: Adding new member consumer-console-consumer-23376-1-344f1d54-a521-49c4-9d6d-e6b772868452 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:04:50,556] INFO [GroupCoordinator 0]: Stabilized group console-consumer-23376 generation 1 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:04:50,562] INFO [GroupCoordinator 0]: Assignment received from leader for group console-consumer-23376 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:04:58,131] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group order in Empty state. Created a new member id consumer-3-781f064f-d933-40d3-9c1a-1a27d9fcf32e for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:04:58,131] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 14 (__consumer_offsets-0) (reason: Adding new member consumer-3-781f064f-d933-40d3-9c1a-1a27d9fcf32e with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:04:58,132] INFO [GroupCoordinator 0]: Stabilized group order generation 15 (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:04:58,136] INFO [GroupCoordinator 0]: Assignment received from leader for group order for generation 15 (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:05:06,048] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-781f064f-d933-40d3-9c1a-1a27d9fcf32e] in group order has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:05:06,049] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 15 (__consumer_offsets-0) (reason: removing member consumer-3-781f064f-d933-40d3-9c1a-1a27d9fcf32e on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:05:06,049] INFO [GroupCoordinator 0]: Group order with generation 16 is now empty (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:05:54,260] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group order in Empty state. Created a new member id consumer-3-a81ce087-0e1f-4e61-82bd-6112e41f5648 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:05:54,261] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 16 (__consumer_offsets-0) (reason: Adding new member consumer-3-a81ce087-0e1f-4e61-82bd-6112e41f5648 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:05:54,261] INFO [GroupCoordinator 0]: Stabilized group order generation 17 (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:05:54,268] INFO [GroupCoordinator 0]: Assignment received from leader for group order for generation 17 (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:06:03,978] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-a81ce087-0e1f-4e61-82bd-6112e41f5648] in group order has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:06:03,978] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 17 (__consumer_offsets-0) (reason: removing member consumer-3-a81ce087-0e1f-4e61-82bd-6112e41f5648 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:06:03,978] INFO [GroupCoordinator 0]: Group order with generation 18 is now empty (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:06:40,474] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group order in Empty state. Created a new member id consumer-3-b01a7fcd-86bf-4c2b-be13-8549a87f60bd for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:06:40,475] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 18 (__consumer_offsets-0) (reason: Adding new member consumer-3-b01a7fcd-86bf-4c2b-be13-8549a87f60bd with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:06:40,476] INFO [GroupCoordinator 0]: Stabilized group order generation 19 (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:06:40,480] INFO [GroupCoordinator 0]: Assignment received from leader for group order for generation 19 (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:07:08,756] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-b01a7fcd-86bf-4c2b-be13-8549a87f60bd] in group order has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:07:08,757] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 19 (__consumer_offsets-0) (reason: removing member consumer-3-b01a7fcd-86bf-4c2b-be13-8549a87f60bd on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:07:08,757] INFO [GroupCoordinator 0]: Group order with generation 20 is now empty (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:13:10,799] INFO [GroupMetadataManager brokerId=0] Group console-consumer-91105 transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManager)
[2021-08-17 17:13:10,799] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-08-17 17:23:10,799] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-08-17 17:33:10,799] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-08-17 17:39:01,471] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-08-17 17:39:01,476] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2021-08-17 17:39:01,477] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2021-08-17 17:39:01,488] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-feb99520-546d-40f6-8c04-db834c156637] in group delivery has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:39:01,488] INFO [GroupCoordinator 0]: Preparing to rebalance group delivery in state PreparingRebalance with old generation 9 (__consumer_offsets-46) (reason: removing member consumer-3-feb99520-546d-40f6-8c04-db834c156637 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:39:01,489] INFO [GroupCoordinator 0]: Group delivery with generation 10 is now empty (__consumer_offsets-46) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:39:01,498] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-console-consumer-23376-1-344f1d54-a521-49c4-9d6d-e6b772868452] in group console-consumer-23376 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:39:01,498] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-23376 in state PreparingRebalance with old generation 1 (__consumer_offsets-12) (reason: removing member consumer-console-consumer-23376-1-344f1d54-a521-49c4-9d6d-e6b772868452 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:39:01,498] INFO [GroupCoordinator 0]: Group console-consumer-23376 with generation 2 is now empty (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2021-08-17 17:39:01,792] WARN Session 0x1000133923c0000 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
[2021-08-17 17:39:01,899] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2021-08-17 17:39:01,899] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2021-08-17 17:39:03,315] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:03,317] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:03,419] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2021-08-17 17:39:04,795] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:04,797] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:06,665] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:06,665] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:08,611] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:08,612] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:10,438] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:10,439] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:12,476] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:12,477] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:14,217] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:14,218] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:16,241] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:16,242] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:18,226] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:18,227] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:19,838] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:19,838] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:21,673] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:21,674] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:21,905] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-08-17 17:39:21,927] INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-08-17 17:39:23,048] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:23,049] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:24,194] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:24,195] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:25,411] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:25,412] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:26,883] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:26,884] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:28,207] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:28,209] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:30,293] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:30,294] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:31,620] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:31,621] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:32,958] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:32,959] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:34,959] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:34,960] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:36,726] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:36,727] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:38,468] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:38,470] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:39,655] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:39,657] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:40,971] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:40,972] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:42,699] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:42,701] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:44,426] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:44,427] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:45,860] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:45,861] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:47,579] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:47,580] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:49,304] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:49,305] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:50,714] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:50,715] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:52,561] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:52,562] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:54,244] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:54,245] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:55,711] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:55,712] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:57,797] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:57,798] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:59,876] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:39:59,877] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:01,543] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:01,544] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:02,978] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:02,979] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:04,772] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:04,774] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:06,578] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:06,579] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:08,460] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:08,461] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:10,522] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:10,523] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:12,101] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:12,102] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:13,983] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:13,984] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:15,100] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:15,101] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:17,106] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:17,107] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:18,661] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:18,662] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:20,541] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:20,542] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:21,917] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:21,918] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:23,475] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:23,476] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:24,842] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:24,843] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:26,834] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:26,835] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:28,081] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:28,083] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:29,928] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:29,930] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:31,440] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:31,441] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:33,021] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:33,023] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:34,920] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:34,921] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:36,976] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:36,977] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:38,682] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:38,683] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:40,288] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:40,289] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:42,084] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:42,085] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:44,126] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:44,127] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:45,565] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:45,566] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:47,483] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:47,484] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:48,672] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:48,673] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:50,285] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:50,287] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:51,493] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-08-17 17:40:51,495] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
